### ISSUE TITLE
Inclusion of SimpleLogin domains in your list of disposable email providers

### ISSUE THREAD

**Issue by Nikola-Test-for-Proton** [mstfknn/email-providers#2]
Hi, this is Nikola.

I work in Proton's (and SimpleLogin's) Anti-Abuse team and noticed that one of our domains is present in your list of disposable emails. To be more precise, we are referring to the slmail.me domain. 

At Proton, we take anti-abuse especially seriously and would like to work with you on having the abovementioned domain removed from your list. Can you elaborate why this domain is listed? Would it be possible to correct this?

We would appreciate it if you could look into this for us accordingly.

Your patience and understanding are greatly appreciated.

**Comment by Yummy60** [comment]
SL (owned by Proton) is aliasing service that FORBIDS to use it as disposable mail:

[ToS of SL](https://simplelogin.io/terms/)
[Example](https://www.reddit.com/r/Simplelogin/comments/17awckx/warning_from_sl/) (if user will create multiple accounts through SL user will be flagged, if continue - suspended)

**Comment by Yummy60** [comment]
@mstfknn

**Comment by mstfknn** [comment]
Hello,
First of all, sorry for the late conversion; the list includes email providers vulnerable to abuse. Since Simple Login also provides an alias, it is expected to be on this list. For example, when I created an account, it created a disposable email address, coerce_mandatory907@simplelogin.com.

**Comment by Nikola-Test-for-Proton** [comment]
Hello,

Thank you for responding.

Please note that an alias, which is what the address you've specified is, is not the same as a disposable email. 

The aliases you can create with SimpleLogin are permanent and not temporary. Moreover, we take anti-abuse very seriously; you can refer to our Terms and Conditions of Service at https://simplelogin.io/terms/. 

In addition to this, it seems that the Proton Mail domains (pm.me, proton.me, protonmail.com, and protonmail.ch) are also included in your list. May we ask why this is the case for these domains as well? 

If you have any concrete examples of Proton Mail or SimpleLogin addresses being used for malicious purposes, we'd appreciate it if you could share so a proper investigation can be conducted on our end.
